[tool.poetry]
name = "example-app"
version = "0.1.0"
description = ""
authors = ["Bwc9876"]

[tool.poetry.dependencies]
python = "^3.10"
django = "^4.1.3"
django-djazztro = "^0.1.0"

[tool.poetry.group.dev.dependencies]
black = "^22.10.0"

