name: Format
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    formatting:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v3
            - name: Setup PNPM
              uses: pnpm/action-setup@v2
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: "pnpm"
            - uses: actions/setup-python@v4
              with:
                  python-version: 3.11
            - uses: Gr1N/setup-poetry@v8
            - name: Install dependencies
              run: pnpm --filter "root" install && poetry install
            - name: Format code
              run: pnpm run format
            - name: Commit changes
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: "Format"
                  branch: ${{ github.head_ref }}
                  commit_user_name: github-actions[bot]
                  commit_user_email: github-actions[bot]@users.noreply.github.com
