name: Publish
on: workflow_dispatch

jobs:
  publish-python:
    name: Publish Python Package
    runs-on: ubuntu-latest     
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python 
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v8
      - name: Install Dependencies
        run: |
          cd packages/django-djazztro
          poetry install
      - name: Publish Package
        run: |
          cd packages/django-djazztro
          poetry config pypi-token.pypi $PYPI_TOKEN
          poetry publish --build --skip-existing
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
  publish-js:
    name: Publish JS Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3   
      - name: Setup PNPM
        uses: pnpm/action-setup@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
          cache: "pnpm"
      - name: Install Dependencies
        run: pnpm i
      - name: Publish
        run: pnpm -r publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
